#!/bin/bash
#SBATCH -J Trim.fname.code
#SBATCH -p shas
#SBATCH --qos Normal
#SBATCH -t 24:00:00
#SBATCH -N 1
#SBATCH --output=fname.code.Trim.out


module load jdk

#Running Fastqc and Trimming on raw fastq files.

~/fastqc -o ../RawFastq/fname.code*.gz

#Trimming low quality reads and adapters
java -jar -Xmx48G ~/trimmomatic-0.36.jar PE -phred33 \
../RawFastq/fname.code_S43_R1_001.fastq.gz \
../RawFastq/fname.code_S43_R2_001.fastq.gz \
../Trimfiles/fname.code_R1_paired.fastq.gz \
../Trimfiles/fname.code_R1_unpaired.fastq.gz \
../Trimfiles/fname.code_R2_paired.fastq.gz \
../Trimfiles/fname.code_R2_unpaired.fastq.gz \
ILLUMINACLIP:/projects/sdas@colostate.edu/app/Trimmomatic-0.36/adapters/TruSeq3-SE.fa:2:30:10 \
CROP:130 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:50


#Run fastqc on trimmed files

~/fastqc -o ../Trimfastqc/ ../Trimfiles/fname.code*.gz


